apiVersion: v1
kind: LimitRange
metadata:
  name: sbekkerm-autoresearch-limits
  namespace: sbekkerm-autoresearch
spec:
  limits:
    - type: Container
      default:
        cpu: "2"
        memory: 8Gi
      defaultRequest:
        cpu: "1"
        memory: 4Gi
      max:
        cpu: "16"
        memory: 64Gi
        nvidia.com/gpu: "1"
      min:
        cpu: 100m
        memory: 128Mi
    - type: Pod
      max:
        cpu: "32"
        memory: 128Gi
        nvidia.com/gpu: "2"
